{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "keda-demo.fullname" . }}-pdb
  namespace: {{ include "keda-demo.namespace" . }}
  labels:
    {{- include "keda-demo.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "keda-demo.selectorLabels" . | nindent 6 }}
{{- end }}
